### ISSUE TITLE
Error with customizable product order

### ISSUE THREAD

**Issue by Kharabet** [sakgiok/codwfeeplus#1]
Hi, @sakgiok 

Check my test order  for https://ps17demo.sakgiok.gr/en/home-accessories/19-customizable-mug.html
 
There is a bug when you order any customizable product with COD payment method
![image](https://user-images.githubusercontent.com/14793248/52634491-0a284f80-2ed0-11e9-961b-b215bb8f3385.png)

You can see this order in your backoffice, but I recive error page as a customer.
![image](https://user-images.githubusercontent.com/14793248/52634516-16aca800-2ed0-11e9-9516-247aafdeaf32.png)

If i choose another payment option it's okay. 

You can easily reproduce this bug. 

Thank you.

**Comment by sakgiok** [comment]
Thanks for the report @Kharabet 
from what I assume, this is not a codwfeeplus bug but a PrestaShop issue (not really an issue, I'll explain...).

What you're seeing is just a notice and not an error, and the only reason is showing up is because debug mode is active. If debug mode is disabled, the transaction would have been concluded as it should.

The reason you are not seeing this notice with the other payment methods is because, the other two payment methods are not creating a pdf invoice when they are finishing the order. If you had another payment method which produced a pdf invoice, or even if you modified the order status, e.g. "Awaiting Bank Wire Payment" for Bank wire payment, in order to generate a pdf invoice, you would see the exact same notice as you described (I tested all this of course and had the above results).

The order is finishing as it should with no other issues, so as long as the debug mode is off (as it should at an active shop) everything is fine.

I'm closing this issue for now.
Thank you again for your input.
